apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste2-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: teste2-pod
      labels:
        app: teste2-pod
      spec:
        containers:
          - name: teste2-container
            image: zeckdevops/teste2:1.1
            env:
              - name: TWORPTEST
                valueFrom:
                  secretKeyRef:
                    name: teste2-secret
                    key: TWORPTEST
  selector:
    matchLabels:
      app: teste2-pod